Repository Volgarenok/spbspu-labs-2024-aap-a, pull requests merged in 2024-10, with the labels that each got.

#1 dobsov.sergey/P0
  dobsov.sergey/P0/main.cpp
Labels: fine

#3 savintsev.ilya/P0
  savintsev.ilya/P0/main.cpp
Labels: fine

#20 maslov.aleksey/P0
  maslov.aleksey/P0/main.cpp
Labels: fine

#11 aleksandrov.igor/P0
  aleksandrov.igor/P0/main.cpp
Labels: fine

#7 maslevtsov.stanislav/P0
  maslevtsov.stanislav/P0/main.cpp
Labels: fine

#21 kushekbaev.danil/P0
  kushekbaev.danil/P0/main.cpp
Labels: fine

#5 demehin.maxim/P0
  demehin.maxim/P0/main.cpp
Labels: fine

#8 abramov.vladislav/P0
  abramov.vladislav/P0/main.cpp
Labels: fine

#32 mozhegova.maria/P0
  mozhegova.maria/P0/main.cpp
Labels: fine

#12 nikonov.andrew/p0
  nikonov.andrew/P0/main.cpp
Labels: fine

#26 rychkov.mihail/P0
  rychkov.mihail/P0/main.cpp
Labels: fine

#25 lanovenko.ivan/P0
  lanovenko.ivan/P0/main.cpp
Labels: fine

#10 hismatova.elizaveta/P0
  hismatova.elizaveta/P0/main.cpp
Labels: fine

#2 maslovskiy.vladislav/P0
  maslovskiy.vladislav/P0/main.cpp
Labels: fine

#15 lebedev.alexandr/P0
  lebedev.alexandr/P0/main.cpp
Labels: fine

#36 petrov.nikita/P0
  petrov.nikita/P0/main.cpp
Labels: fine

#18 alymova.ksenia/P0
  alymova.ksenia/P0/main.cpp
Labels: fine

#30 shabalin.dmitrij/p0
  shabalin.dmitrij/P0/main.cpp
Labels: fine

#31 smirnov.alexandr/P0
  smirnov.alexandr/P0/main.cpp
Labels: fine

#13 kizhin.evgeniy/P0
  kizhin.evgeniy/P0/main.cpp
Labels: fine

#9 tkach.danil/P0
  tkach.danil/P0/main.cpp
Labels: fine

#6 shramko.maksim/P0
  shramko.maksim/P0/main.cpp
Labels: fine

#14 duhanina.alina/P0
  duhanina.alina/P0/main.cpp
Labels: fine

#39 evstyunichev.konstantin/P0
  evstyunichev.konstantin/P0/main.cpp
Labels: fine

#17 Guseynov.guseyn/p0
  guseynov.guseyn/P0/main.cpp
Labels: fine

#23 balashov.dima/P0
  balashov.dima/P0/main.cpp
Labels: fine

#16 Karnauhova.alexandra/p0
  karnauhova.alexandra/P0/main.cpp
Labels: fine

#37 sharifullina.sofia/P0
  sharifullina.sofia/P0/main.cpp
Labels: fine

#38 Brevnov.nikita/p0
  brevnov.nikita/P0/main.cpp
Labels: fine

#44 belobrov.timofey/P0
  belobrov.timofey/P0/main.cpp
Labels: fine

#41 sveshnikov.michail/P0
  sveshnikov.michail/P0/main.cpp
Labels: fine

#42 gavrilova.polina/P0
  gavrilova.polina/P0/main.cpp
Labels: fine

#46 krylov.matvey/P0
  krylov.matvey/P0/main.cpp
Labels: fine

#33 dribas.sergey/p0
  dribas.sergey/P0/main.cpp
Labels: fine

#45 komarova.anastasia/P0
  komarova.anastasia/P0/main.cpp
Labels: fine

#35 zholobov.oleg/P0
  zholobov.oleg/P0/main.cpp
Labels: fine

#43 cherkasov.nikita/p0
  cherkasov.nikita/P0/main.cpp
Labels: fine

#61 timofeev.maxim/P0
  timofeev.maxim/P0/main.cpp
Labels: fine

#50 asafov.andrew/P0
  asafov.andrew/P0/main.cpp
Labels: fine

#68 Lungu.george/P0
  lungu.george/P0/main.cpp
Labels: fine

#60 dirti.aldyn/P0
  dirti.aldyn/P0/main.cpp
Labels: fine

#76 bocharov.egor/P0
  bocharov.egor/P0/main.cpp
Labels: fine

#84 rychkov.mihail/P2
  rychkov.mihail/P2/comparison_table.cpp
  rychkov.mihail/P2/comparison_table.hpp
  rychkov.mihail/P2/main.cpp
  rychkov.mihail/P2/taylors_series.cpp
  rychkov.mihail/P2/taylors_series.hpp
Labels: fine, gr 1

#79 shramko.maksim/P2
  shramko.maksim/P2/main.cpp
  shramko.maksim/P2/partOfTaylor.cpp
  shramko.maksim/P2/partOfTaylor.hpp
  shramko.maksim/P2/rowOutput.cpp
  shramko.maksim/P2/rowOutput.hpp
Labels: fine, gr 1

#95 petrov.nikita/P2
  petrov.nikita/P2/calculate_sinh.hpp
  petrov.nikita/P2/calculatebystd.cpp
  petrov.nikita/P2/calculatebytaylor.cpp
  petrov.nikita/P2/main.cpp
  petrov.nikita/P2/outputtable.cpp
Labels: fine, gr 1

#82 tkach.danil/P2
  tkach.danil/P2/main.cpp
  tkach.danil/P2/output_row.cpp
  tkach.danil/P2/output_table.cpp
  tkach.danil/P2/stdmath.cpp
  tkach.danil/P2/tableoutput.h
  tkach.danil/P2/taylor.cpp
  tkach.danil/P2/taylorrow.h
Labels: fine, gr 1

#83 maslov.aleksey/P2
  maslov.aleksey/P2/main.cpp
  maslov.aleksey/P2/taylorSeries.cpp
  maslov.aleksey/P2/taylorSeries.hpp
Labels: fine, gr 1

#56 mozhegova.maria/P2
  mozhegova.maria/P2/main.cpp
  mozhegova.maria/P2/output.cpp
  mozhegova.maria/P2/output.hpp
  mozhegova.maria/P2/uno_div_cube.cpp
  mozhegova.maria/P2/uno_div_cube.hpp
Labels: fine, gr 1

#74 timofeev.maxim/P2
  timofeev.maxim/P2/MatrixOutput.cpp
  timofeev.maxim/P2/arctanTaylor.cpp
  timofeev.maxim/P2/arctanTaylor.h
  timofeev.maxim/P2/main.cpp
Labels: fine, gr 1

#58 gavrilova.polina/P2
  gavrilova.polina/P2/main.cpp
  gavrilova.polina/P2/tailor_series.cpp
  gavrilova.polina/P2/tailor_series.hpp
Labels: fine, gr 5

#52 evstyunichev.konstantin/P2
  evstyunichev.konstantin/P2/arcsin.cpp
  evstyunichev.konstantin/P2/arcsin.hpp
  evstyunichev.konstantin/P2/main.cpp
Labels: fine, gr 5

#63 dribas.sergey/P2
  dribas.sergey/P2/main.cpp
  dribas.sergey/P2/outres.cpp
  dribas.sergey/P2/outres.hpp
  dribas.sergey/P2/taylor.cpp
  dribas.sergey/P2/taylor.hpp
Labels: fine, gr 5

#62 kizhin.evgeniy/P2
  kizhin.evgeniy/P2/main.cpp
  kizhin.evgeniy/P2/printing_utils.cpp
  kizhin.evgeniy/P2/printing_utils.hpp
  kizhin.evgeniy/P2/taylor_cosh.cpp
  kizhin.evgeniy/P2/taylor_cosh.hpp
Labels: fine, gr 5

#90 karnauhova.alexandra/P2
  karnauhova.alexandra/P2/count_sin.cpp
  karnauhova.alexandra/P2/count_sin.hpp
  karnauhova.alexandra/P2/create_table.cpp
  karnauhova.alexandra/P2/create_table.hpp
  karnauhova.alexandra/P2/main.cpp
Labels: fine, gr 5

#54 kiselev.sergey/P2
  kiselev.sergey/P2/check_interval.cpp
  kiselev.sergey/P2/main.cpp
  kiselev.sergey/P2/output_table.cpp
  kiselev.sergey/P2/sqr_unox.cpp
  kiselev.sergey/P2/taylor.cpp
  kiselev.sergey/P2/taylor.h
Labels: fine, gr 5

#53 balashov.dima/P2
  balashov.dima/P2/main.cpp
  balashov.dima/P2/tableDisplay.cpp
  balashov.dima/P2/tableDisplay.hpp
  balashov.dima/P2/taylorsRow.cpp
  balashov.dima/P2/taylorsRow.hpp
Labels: fine, gr 1

#86 finaev.alexey/P2
  finaev.alexey/P2/base_tyler.cpp
  finaev.alexey/P2/final_output.cpp
  finaev.alexey/P2/main.cpp
  finaev.alexey/P2/tyler_row.cpp
  finaev.alexey/P2/tyler_row.h
Labels: fine, gr 1

#51 demehin.maxim/P2
  demehin.maxim/P2/main.cpp
  demehin.maxim/P2/output.cpp
  demehin.maxim/P2/taylor.cpp
  demehin.maxim/P2/taylor.h
Labels: fine, gr 5

#59 abramov.vladislav/P2
  abramov.vladislav/P2/main.cpp
  abramov.vladislav/P2/tablePrint.cpp
  abramov.vladislav/P2/taylorPolynomial.cpp
  abramov.vladislav/P2/taylorPolynomial.hpp
Labels: fine, black-mark, gr 4

#88 hismatova.elizaveta/P2
  hismatova.elizaveta/P2/main.cpp
  hismatova.elizaveta/P2/taylor.cpp
  hismatova.elizaveta/P2/taylor.h
Labels: fine, gr 1
