Repository Volgarenok/spbspu-labs-2024-aap-a, pull requests merged in 2024-12, with the labels that each got.

#191 savintsev.ilya/p6
  savintsev.ilya/P6/checkuniquechars.cpp
  savintsev.ilya/P6/checkuniquechars.h
  savintsev.ilya/P6/main.cpp
  savintsev.ilya/common/newlineterminatedstr.cpp
Labels: fine, gr 4

#187 smirnov.alexandr/P4
  smirnov.alexandr/P4/main.cpp
  smirnov.alexandr/P4/unionString.cpp
  smirnov.alexandr/P4/unionString.hpp
Labels: fine, gr 1

#162 shramko.maksim/P4
  shramko.maksim/P4/main.cpp
  shramko.maksim/P4/modifyString.cpp
  shramko.maksim/P4/modifyString.hpp
Labels: fine, gr 1

#200 kiselev.sergey/p6
  kiselev.sergey/P6/isExpression.cpp
  kiselev.sergey/P6/isExpression.h
  kiselev.sergey/P6/main.cpp
  kiselev.sergey/common/inputString.cpp
  kiselev.sergey/common/inputString.h
Labels: fine, gr 5

#109 belobrov.timofey/P3
  belobrov.timofey/P3/fileIO.cpp
  belobrov.timofey/P3/fileIO.hpp
  belobrov.timofey/P3/main.cpp
  belobrov.timofey/P3/matrixTransform.cpp
  belobrov.timofey/P3/matrixTransform.hpp
Labels: fine, gr 4, minus 1

#193 duhanina.alina/P6
  duhanina.alina/P6/main.cpp
  duhanina.alina/P6/recursiveChecks.cpp
  duhanina.alina/P6/recursiveChecks.h
Labels: fine, gr 5

#185 lebedev.alexandr/P4
  lebedev.alexandr/P4/main.cpp
  lebedev.alexandr/P4/rmv_vow.cpp
  lebedev.alexandr/P4/rmv_vow.hpp
Labels: fine, gr 1

#158 nikonov.andrew/P4
  nikonov.andrew/P4/formline.cpp
  nikonov.andrew/P4/formline.hpp
  nikonov.andrew/P4/main.cpp
  nikonov.andrew/common/dynamicArray.cpp
  nikonov.andrew/common/dynamicArray.hpp
Labels: fine, gr 4

#201 Brevnov.nikita/P6
  brevnov.nikita/P6/isexpression.cpp
  brevnov.nikita/P6/isexpression.hpp
  brevnov.nikita/P6/main.cpp
  brevnov.nikita/common/getline.cpp
  brevnov.nikita/common/getline.hpp
Labels: fine, gr 5

#220 timofeev.maxim/P4
  timofeev.maxim/P4/has_sam_set.h
  timofeev.maxim/P4/input_line.cpp
  timofeev.maxim/P4/main.cpp
  timofeev.maxim/P4/same_symbols.cpp
Labels: fine, gr 1

#207 aleksandrov.igor/P6
  aleksandrov.igor/P6/floatLiteralCheck.cpp
  aleksandrov.igor/P6/floatLiteralCheck.h
  aleksandrov.igor/P6/main.cpp
  aleksandrov.igor/common/getString.cpp
  aleksandrov.igor/common/getString.h
Labels: fine, gr 4

#219 Bocharov.egor/p3
  bocharov.egor/P3/change_matrix.cpp
  bocharov.egor/P3/check.cpp
  bocharov.egor/P3/find_local_maximum.cpp
  bocharov.egor/P3/input_matrix.cpp
  bocharov.egor/P3/main.cpp
  bocharov.egor/P3/matrix.h
  bocharov.egor/P3/output_matrix.cpp
Labels: fine, gr 5, minus 1

#174 hismatova.elizaveta/P4
  hismatova.elizaveta/P4/check_string.cpp
  hismatova.elizaveta/P4/check_string.h
  hismatova.elizaveta/P4/main.cpp
Labels: fine, gr 1

#166 averenkov.eugene/P4
  averenkov.eugene/P4/lattwo.cpp
  averenkov.eugene/P4/lattwo.h
  averenkov.eugene/P4/main.cpp
  averenkov.eugene/common/dynamicinput.cpp
  averenkov.eugene/common/dynamicinput.h
Labels: fine, gr 5

#183 Zakirov.marat/p4
  zakirov.marat/P4/line_processing.cpp
  zakirov.marat/P4/line_processing.hpp
  zakirov.marat/P4/main.cpp
  zakirov.marat/common/resize_line.cpp
  zakirov.marat/common/resize_line.hpp
Labels: fine, gr 4

#192 nikonov.andrew/P6
  nikonov.andrew/P4/main.cpp
  nikonov.andrew/P6/main.cpp
  nikonov.andrew/P6/string_check.cpp
  nikonov.andrew/P6/string_check.hpp
  nikonov.andrew/common/dynamicArray.cpp
Labels: fine, gr 4

#142 kushekbaev.danil/P3
  kushekbaev.danil/P3/countSaddlePoints.cpp
  kushekbaev.danil/P3/count_saddle_point.hpp
  kushekbaev.danil/P3/main.cpp
Labels: fine, gr 4, minus 1

#154 guseynov.guseyn/P4
  guseynov.guseyn/P4/det_Num_Of_Letters.cpp
  guseynov.guseyn/P4/det_Num_Of_Letters.hpp
  guseynov.guseyn/P4/main.cpp
  guseynov.guseyn/common/workWithString.cpp
  guseynov.guseyn/common/workWithString.hpp
Labels: fine, gr 1

#222 sveshnikov.michail/P6
  sveshnikov.michail/P6/is_real_number.cpp
  sveshnikov.michail/P6/is_real_number.hpp
  sveshnikov.michail/P6/main.cpp
Labels: fine, gr 4

#134 evstyunichev.konstantin/P3
  evstyunichev.konstantin/P3/main.cpp
  evstyunichev.konstantin/P3/matrix.cpp
  evstyunichev.konstantin/P3/matrix.hpp
Labels: fine, gr 5, minus 1

#108 gavrilova.polina/P3
  gavrilova.polina/P3/input_matrix.cpp
  gavrilova.polina/P3/main.cpp
  gavrilova.polina/P3/upptri.cpp
  gavrilova.polina/P3/upptri.hpp
Labels: fine, gr 5, minus 1

#145 dirti.aldyn/P2
  dirti.aldyn/P2/main.cpp
  dirti.aldyn/P2/taylor.cpp
  dirti.aldyn/P2/taylor.hpp
Labels: fine, gr 5, minus 2

#119 cherkasov.nikita/P3
  cherkasov.nikita/P3/main.cpp
  cherkasov.nikita/P3/matrix.cpp
  cherkasov.nikita/P3/matrix.h
Labels: fine, gr 4, minus 2

#140 asafov.andrew/P3
  asafov.andrew/P3/main.cpp
  asafov.andrew/P3/matrixHandling.cpp
  asafov.andrew/P3/matrixHandling.hpp
  asafov.andrew/P3/matrixInitialization.cpp
  asafov.andrew/P3/matrixInitiallization.hpp
  asafov.andrew/P3/matrixOutput.cpp
  asafov.andrew/P3/matrixOutput.hpp
Labels: fine, gr 4, minus 2

#94 Lungu.george/P2
  lungu.george/P2/Tylor.cpp
  lungu.george/P2/Tylor.h
  lungu.george/P2/main.cpp
Labels: fine, gr 4, minus 2

#227 sharifullina.sofia/P3
  sharifullina.sofia/P3/main.cpp
  sharifullina.sofia/P3/matrix.cpp
  sharifullina.sofia/P3/matrix.hpp
Labels: fine, gr 1, minus 1

#198 demehin.maxim/P6
  demehin.maxim/P6/is_expr.h
  demehin.maxim/P6/main.cpp
  demehin.maxim/P6/vocabs.cpp
Labels: fine, gr 5

#228 petrov.nikita/P6
  petrov.nikita/P4/main.cpp
  petrov.nikita/P4/making_new_cstring.hpp
  petrov.nikita/P6/is_real_number.cpp
  petrov.nikita/P6/is_real_number.hpp
  petrov.nikita/P6/main.cpp
  petrov.nikita/common/input_cstring.cpp
  petrov.nikita/common/input_cstring.hpp
Labels: fine, gr 1

#231 shramko.maksim/P6
  shramko.maksim/P4/countConsecutiveIdenticalSymbols.cpp
  shramko.maksim/P4/countConsecutiveIdenticalSymbols.hpp
  shramko.maksim/P4/main.cpp
  shramko.maksim/P6/isExpression.cpp
  shramko.maksim/P6/isExpression.hpp
  shramko.maksim/P6/main.cpp
  shramko.maksim/common/inputString.cpp
  shramko.maksim/common/inputString.hpp
Labels: fine, gr 1

#163 kushekbaev.danil/P4
  kushekbaev.danil/P4/hasCommonChars.cpp
  kushekbaev.danil/P4/has_common_chars.hpp
  kushekbaev.danil/P4/main.cpp
  kushekbaev.danil/common/readInputArray.cpp
  kushekbaev.danil/common/read_input_array.hpp
Labels: fine, gr 4, minus 1

#180 dribas.sergey/P4
  dribas.sergey/P4/difLat.cpp
  dribas.sergey/P4/difLat.hpp
  dribas.sergey/P4/main.cpp
  dribas.sergey/common/enterStr.cpp
  dribas.sergey/common/enterStr.hpp
Labels: fine, gr 5, minus 2

#153 evstyunichev.konstantin/P4
  evstyunichev.konstantin/P4/cstrings.cpp
  evstyunichev.konstantin/P4/cstrings.hpp
  evstyunichev.konstantin/P4/main.cpp
Labels: fine, black-mark, gr 5, minus 1

#225 timofeev.maxim/P6
  timofeev.maxim/P6/main.cpp
  timofeev.maxim/P6/real_number_set.cpp
  timofeev.maxim/P6/real_number_set.h
  timofeev.maxim/common/input_line.cpp
  timofeev.maxim/common/input_line.h
Labels: fine, gr 1

#230 smirnov.alexandr/P6
  smirnov.alexandr/P4/main.cpp
  smirnov.alexandr/P4/unionString.cpp
  smirnov.alexandr/P4/unionString.hpp
  smirnov.alexandr/P6/checkString.cpp
  smirnov.alexandr/P6/checkString.hpp
  smirnov.alexandr/P6/main.cpp
  smirnov.alexandr/common/getLine.cpp
  smirnov.alexandr/common/getLine.hpp
Labels: fine, gr 1

#208 guseynov.guseyn/P6
  guseynov.guseyn/P4/main.cpp
  guseynov.guseyn/P6/is_double.cpp
  guseynov.guseyn/P6/is_double.hpp
  guseynov.guseyn/P6/main.cpp
  guseynov.guseyn/common/workWithString.cpp
Labels: fine, gr 1

#173 maslovskiy.vladislav/P4
  maslovskiy.vladislav/P4/main.cpp
  maslovskiy.vladislav/P4/mergeStrs.cpp
  maslovskiy.vladislav/P4/mergeStrs.hpp
  maslovskiy.vladislav/common/getLine.cpp
  maslovskiy.vladislav/common/getLine.hpp
Labels: fine, gr 4, minus 2

#211 krylov.matvey/P6
  krylov.matvey/P6/checkLineOnFloat.cpp
  krylov.matvey/P6/checkLineOnFloat.hpp
  krylov.matvey/P6/main.cpp
Labels: fine, gr 4

#216 Zakirov.marat/p6
  zakirov.marat/P6/CheckRealNumber.cpp
  zakirov.marat/P6/CheckRealNumber.hpp
  zakirov.marat/P6/main.cpp
Labels: fine, gr 4

#146 lanovenko.ivan/P3
  lanovenko.ivan/P3/input_matrix.cpp
  lanovenko.ivan/P3/input_matrix.h
  lanovenko.ivan/P3/main.cpp
  lanovenko.ivan/P3/modification_matrix.cpp
  lanovenko.ivan/P3/modification_matrix.h
  lanovenko.ivan/P3/output_matrix.cpp
  lanovenko.ivan/P3/output_matrix.h
Labels: fine, gr 1, minus 1

#143 komarova.anastasia/P3
  komarova.anastasia/P2/Tei.cpp
  komarova.anastasia/P2/ln_T.cpp
  komarova.anastasia/P2/output.cpp
  komarova.anastasia/P3/main.cpp
  komarova.anastasia/P3/matrix.cpp
  komarova.anastasia/P3/matrix.h
Labels: fine, gr 4, minus 1

#190 kushekbaev.danil/P6
  kushekbaev.danil/P6/isValidExpression.cpp
  kushekbaev.danil/P6/is_valid_expression.hpp
  kushekbaev.danil/P6/main.cpp
Labels: fine, gr 4

#224 evstyunichev.konstantin/P6
  evstyunichev.konstantin/P4/cstrings.cpp
  evstyunichev.konstantin/P4/cstrings.hpp
  evstyunichev.konstantin/P4/main.cpp
  evstyunichev.konstantin/P6/expression_check.cpp
  evstyunichev.konstantin/P6/expression_check.hpp
  evstyunichev.konstantin/P6/main.cpp
  evstyunichev.konstantin/common/input_string.cpp
  evstyunichev.konstantin/common/input_string.hpp
Labels: fine, gr 5

#189 cherkasov.nikita/P4
  cherkasov.nikita/P4/main.cpp
  cherkasov.nikita/P4/replaceChar.cpp
  cherkasov.nikita/P4/replaceChar.h
  cherkasov.nikita/common/getLine.cpp
  cherkasov.nikita/common/getLine.h
Labels: fine, gr 4, minus 1

#229 lebedev.alexandr/P6
  lebedev.alexandr/P4/main.cpp
  lebedev.alexandr/P4/rmv_vow.cpp
  lebedev.alexandr/P4/rmv_vow.hpp
  lebedev.alexandr/P6/isExpression.cpp
  lebedev.alexandr/P6/isExpression.hpp
  lebedev.alexandr/P6/main.cpp
  lebedev.alexandr/common/getLine.cpp
  lebedev.alexandr/common/getLine.hpp
Labels: fine, gr 1

#175 gavrilova.polina/P4
  gavrilova.polina/P4/main.cpp
  gavrilova.polina/P4/rm_digits.cpp
  gavrilova.polina/P4/rm_digits.hpp
  gavrilova.polina/common/inputStr.cpp
  gavrilova.polina/common/inputStr.hpp
Labels: fine, gr 5, minus 2

#210 cherkasov.nikita/P6
  cherkasov.nikita/P6/main.cpp
  cherkasov.nikita/P6/readLine.cpp
  cherkasov.nikita/P6/readLine.h
  cherkasov.nikita/P6/validNumber.cpp
  cherkasov.nikita/P6/validNumber.h
Labels: fine, gr 4

#205 hismatova.elizaveta/P6
  hismatova.elizaveta/P4/check_string.cpp
  hismatova.elizaveta/P4/check_string.h
  hismatova.elizaveta/P4/main.cpp
  hismatova.elizaveta/P6/main.cpp
  hismatova.elizaveta/P6/suitable_string.cpp
  hismatova.elizaveta/P6/suitable_string.h
  hismatova.elizaveta/common/get_string.cpp
  hismatova.elizaveta/common/get_string.h
Labels: fine, gr 1

#223 gavrilova.polina/P6
  gavrilova.polina/P6/expressions.cpp
  gavrilova.polina/P6/expressions.hpp
  gavrilova.polina/P6/main.cpp
Labels: fine, gr 5

#206 maslovskiy.vladislav/P6
  maslovskiy.vladislav/P6/main.cpp
  maslovskiy.vladislav/P6/recursionString.cpp
  maslovskiy.vladislav/P6/recursionString.hpp
Labels: fine, gr 4

#194 averenkov.eugene/P6
  averenkov.eugene/P6/isReal.cpp
  averenkov.eugene/P6/isReal.h
  averenkov.eugene/P6/main.cpp
Labels: fine, gr 5

#237 Bocharov.egor/p4
  bocharov.egor/P4/main.cpp
  bocharov.egor/P4/string_processing.cpp
  bocharov.egor/P4/string_processing.h
  bocharov.egor/common/getline.cpp
  bocharov.egor/common/getline.h
Labels: fine, gr 5, minus 1

#234 dribas.sergey/P6
  dribas.sergey/P6/isValidString.cpp
  dribas.sergey/P6/isValidString.hpp
  dribas.sergey/P6/main.cpp
  dribas.sergey/common/enterStr.cpp
Labels: fine, gr 5

#239 sharifullina.sofia/P4
  sharifullina.sofia/P4/main.cpp
  sharifullina.sofia/P4/shrSym_uniTwo.cpp
  sharifullina.sofia/P4/shrSym_uniTwo.hpp
Labels: fine, gr 1, minus 1

#168 lanovenko.ivan/P4
  lanovenko.ivan/P4/main.cpp
  lanovenko.ivan/P4/strconversion.cpp
  lanovenko.ivan/P4/strconversion.h
Labels: fine, gr 1, minus 1

#217 lanovenko.ivan/p6
  lanovenko.ivan/P6/main.cpp
  lanovenko.ivan/P6/string_check.cpp
  lanovenko.ivan/P6/string_check.h
  lanovenko.ivan/common/strinput.cpp
  lanovenko.ivan/common/strinput.h
Labels: fine, gr 1

#255 Komarova.anastasia/p4
  komarova.anastasia/P4/change.h
  komarova.anastasia/P4/change_string.cpp
  komarova.anastasia/P4/dynamic.cpp
  komarova.anastasia/P4/dynamic.h
  komarova.anastasia/P4/main.cpp
  komarova.anastasia/P4/rep_sym.cpp
Labels: fine, gr 4, minus 1

#131 Shabalin.dmitrij/p3
  shabalin.dmitrij/P3/iomatrix.cpp
  shabalin.dmitrij/P3/iomatrix.hpp
  shabalin.dmitrij/P3/main.cpp
  shabalin.dmitrij/P3/matrix_operations.cpp
  shabalin.dmitrij/P3/matrix_operations.hpp
Labels: fine, gr 5, minus 1

#182 Shabalin.dmitrij/p4
  shabalin.dmitrij/P4/inputOfString.cpp
  shabalin.dmitrij/P4/inputOfString.h
  shabalin.dmitrij/P4/main.cpp
  shabalin.dmitrij/P4/removeVowels.cpp
  shabalin.dmitrij/P4/removeVowels.h
Labels: fine, gr 5, minus 1
