Repository Volgarenok/spbspu-labs-2024-aap-a, pull requests merged in 2024-11, with the labels that each got.

#64 aleksandrov.igor/P2
  aleksandrov.igor/P2/main.cpp
  aleksandrov.igor/P2/row.cpp
  aleksandrov.igor/P2/row.h
  aleksandrov.igor/P2/taylor.cpp
  aleksandrov.igor/P2/taylor.h
Labels: fine, gr 4

#96 lanovenko.ivan/P2
  lanovenko.ivan/P2/main.cpp
  lanovenko.ivan/P2/sqruno.cpp
  lanovenko.ivan/P2/table.cpp
  lanovenko.ivan/P2/taylorseries.cpp
  lanovenko.ivan/P2/taylorseries.h
Labels: fine, gr 1

#65 savintsev.ilya/p2
  savintsev.ilya/P2/interactterminal.cpp
  savintsev.ilya/P2/interactterminal.h
  savintsev.ilya/P2/main.cpp
  savintsev.ilya/P2/mathematics.cpp
  savintsev.ilya/P2/mathematics.h
Labels: fine, gr 4

#85 krylov.matvey/P2
  krylov.matvey/P2/calculateMathValues.cpp
  krylov.matvey/P2/calculateMathValues.hpp
  krylov.matvey/P2/main.cpp
  krylov.matvey/P2/outputTable.cpp
  krylov.matvey/P2/outputTable.hpp
Labels: fine, gr 4

#69 maslevtsov.stanislav/P2
  maslevtsov.stanislav/P2/main.cpp
  maslevtsov.stanislav/P2/table_output.cpp
  maslevtsov.stanislav/P2/table_output.hpp
  maslevtsov.stanislav/P2/taylor_series.cpp
  maslevtsov.stanislav/P2/taylor_series.hpp
Labels: fine, gr 4

#91 Zakirov.marat/p2
  zakirov.marat/P2/CreatingTables.cpp
  zakirov.marat/P2/CreatingTables.hpp
  zakirov.marat/P2/FindingTylor.cpp
  zakirov.marat/P2/FindingTylor.hpp
  zakirov.marat/P2/main.cpp
Labels: fine, gr 4

#97 smirnov.alexandr/P2
  smirnov.alexandr/P2/main.cpp
  smirnov.alexandr/P2/table.cpp
  smirnov.alexandr/P2/table.hpp
  smirnov.alexandr/P2/taylorSeries.cpp
  smirnov.alexandr/P2/taylorSeries.hpp
Labels: fine, gr 1

#67 lebedev.alexandr/P2
  lebedev.alexandr/P2/main.cpp
  lebedev.alexandr/P2/output.cpp
  lebedev.alexandr/P2/output.hpp
  lebedev.alexandr/P2/taylor_raw.cpp
  lebedev.alexandr/P2/taylor_raw.hpp
Labels: fine, gr 1

#77 duhanina.alina/P2
  duhanina.alina/P2/calcValue.cpp
  duhanina.alina/P2/calcValueStd.cpp
  duhanina.alina/P2/main.cpp
  duhanina.alina/P2/output.cpp
  duhanina.alina/P2/titletaylor.h
Labels: fine, gr 5

#55 nikonov.andrew/P2
  nikonov.andrew/P2/main.cpp
  nikonov.andrew/P2/taylor_cos.cpp
  nikonov.andrew/P2/taylor_cos.hpp
  nikonov.andrew/P2/taylor_output.cpp
  nikonov.andrew/P2/taylor_output.hpp
Labels: fine, gr 4

#75 zholobov.oleg/P2
  zholobov.oleg/P2/main.cpp
  zholobov.oleg/P2/taylor_arctg.cpp
  zholobov.oleg/P2/taylor_arctg.hpp
Labels: fine, gr 5

#57 maslovskiy.vladislav/P2
  maslovskiy.vladislav/P2/main.cpp
  maslovskiy.vladislav/P2/tableMaker.cpp
  maslovskiy.vladislav/P2/tableMaker.hpp
  maslovskiy.vladislav/P2/teilorFun.cpp
  maslovskiy.vladislav/P2/teilorFun.hpp
Labels: fine, gr 4

#72 alymova.ksenia/P2
  alymova.ksenia/P2/arctg.cpp
  alymova.ksenia/P2/main.cpp
  alymova.ksenia/P2/print.cpp
  alymova.ksenia/P2/print_error.cpp
  alymova.ksenia/P2/print_row.cpp
  alymova.ksenia/P2/taylor_row.cpp
  alymova.ksenia/P2/taylor_table.h
Labels: fine, gr 4

#93 guseynov.guseyn/P2
  guseynov.guseyn/P2/main.cpp
  guseynov.guseyn/P2/taylor.cpp
  guseynov.guseyn/P2/taylor.hpp
Labels: fine, gr 1

#66 belobrov.timofey/P2
  belobrov.timofey/P2/f_teylor.cpp
  belobrov.timofey/P2/f_teylor.hpp
  belobrov.timofey/P2/main.cpp
  belobrov.timofey/P2/output.cpp
  belobrov.timofey/P2/output.hpp
Labels: fine, gr 4

#89 sveshnikov.michail/P2
  sveshnikov.michail/P2/main.cpp
  sveshnikov.michail/P2/math.cpp
  sveshnikov.michail/P2/row.cpp
  sveshnikov.michail/P2/table.cpp
  sveshnikov.michail/P2/taylor.cpp
  sveshnikov.michail/P2/taylor.hpp
Labels: fine, gr 4

#80 averenkov.eugene/P2
  averenkov.eugene/P2/main.cpp
  averenkov.eugene/P2/taylor.cpp
  averenkov.eugene/P2/taylor.h
Labels: fine, gr 5

#99 Brevnov.nikita/p2
  brevnov.nikita/P2/createtable.cpp
  brevnov.nikita/P2/createtable.hpp
  brevnov.nikita/P2/main.cpp
  brevnov.nikita/P2/teylor.cpp
  brevnov.nikita/P2/teylor.hpp
Labels: fine, gr 5

#70 kushekbaev.danil/P2
  kushekbaev.danil/P2/main.cpp
  kushekbaev.danil/P2/printResult.cpp
  kushekbaev.danil/P2/printWidth.cpp
  kushekbaev.danil/P2/sinhCalc.cpp
  kushekbaev.danil/P2/sinh_taylor_calculator.hpp
  kushekbaev.danil/P2/taylorCalc.cpp
Labels: fine, gr 4

#71 cherkasov.nikita/P2
  cherkasov.nikita/P2/main.cpp
  cherkasov.nikita/P2/taylor_f.cpp
  cherkasov.nikita/P2/taylor_f.h
Labels: fine, gr 4

#127 rychkov.mihail/P3
  rychkov.mihail/P3/arguments_parsing.cpp
  rychkov.mihail/P3/arguments_parsing.hpp
  rychkov.mihail/P3/get_matrix.cpp
  rychkov.mihail/P3/get_matrix.hpp
  rychkov.mihail/P3/main.cpp
  rychkov.mihail/P3/sum_sdg.cpp
  rychkov.mihail/P3/sum_sdg.hpp
Labels: fine, gr 1

#100 Shabalin.dmitrij/p2
  shabalin.dmitrij/P2/main.cpp
  shabalin.dmitrij/P2/taylorCalc.cpp
  shabalin.dmitrij/P2/taylorCalc.hpp
Labels: fine, gr 5

#87 komarova.anastasia/P2
  komarova.anastasia/P2/Tei.cpp
  komarova.anastasia/P2/ln_T.cpp
  komarova.anastasia/P2/main.cpp
  komarova.anastasia/P2/matherr.cpp
  komarova.anastasia/P2/output.cpp
  komarova.anastasia/P2/tableTeilor.h
Labels: fine, gr 4

#184 rychkov.mihail/P4
  rychkov.mihail/P4/main.cpp
  rychkov.mihail/P4/memf.cpp
  rychkov.mihail/P4/memf.hpp
  rychkov.mihail/P4/string_analysis.cpp
  rychkov.mihail/P4/string_analysis.hpp
  rychkov.mihail/P4/string_input.cpp
  rychkov.mihail/P4/string_input.hpp
Labels: fine, gr 1

#118 nikonov.andrew/P3
  nikonov.andrew/P3/main.cpp
  nikonov.andrew/P3/mtx_transform.cpp
  nikonov.andrew/P3/mtx_transform.hpp
Labels: fine, gr 4

#120 alymova.ksenia/P3
  alymova.ksenia/P3/change_matrix.cpp
  alymova.ksenia/P3/input_matrix.cpp
  alymova.ksenia/P3/main.cpp
  alymova.ksenia/P3/matrix.h
  alymova.ksenia/P3/print_matrix.cpp
Labels: fine, gr 4

#115 dribas.sergey/P3
  dribas.sergey/P3/enterMTX.cpp
  dribas.sergey/P3/enterMTX.hpp
  dribas.sergey/P3/is3Angle.cpp
  dribas.sergey/P3/is3Angle.hpp
  dribas.sergey/P3/main.cpp
Labels: fine, gr 5

#112 maslov.aleksey/P3
  maslov.aleksey/P3/arrays.cpp
  maslov.aleksey/P3/arrays.hpp
  maslov.aleksey/P3/main.cpp
Labels: fine, gr 1

#107 savintsev.ilya/p3
  savintsev.ilya/P3/main.cpp
  savintsev.ilya/P3/matrix.cpp
  savintsev.ilya/P3/matrix.h
Labels: fine, gr 4

#111 demehin.maxim/P3
  demehin.maxim/P3/cnt_row_nsm.cpp
  demehin.maxim/P3/cnt_row_nsm.h
  demehin.maxim/P3/main.cpp
  demehin.maxim/P3/matrix.cpp
  demehin.maxim/P3/matrix.h
Labels: fine, gr 5

#160 maslov.aleksey/P4
  maslov.aleksey/P4/main.cpp
  maslov.aleksey/P4/stringManipulator.cpp
  maslov.aleksey/P4/stringManipulator.hpp
Labels: fine, gr 1

#122 tkach.danil/P3
  tkach.danil/P3/filemtx.h
  tkach.danil/P3/inputmtx.cpp
  tkach.danil/P3/main.cpp
  tkach.danil/P3/mtxcreate.cpp
  tkach.danil/P3/mtxlogic.h
  tkach.danil/P3/outputmtx.cpp
Labels: fine, gr 1

#125 kiselev.sergey/P3
  kiselev.sergey/P3/inputMatrix.cpp
  kiselev.sergey/P3/inputMatrix.h
  kiselev.sergey/P3/main.cpp
  kiselev.sergey/P3/saddleElement.cpp
  kiselev.sergey/P3/saddleElement.h
Labels: fine, gr 5

#81 asafov.andrew/P2
  asafov.andrew/P2/countExpNegPow2x.cpp
  asafov.andrew/P2/countExpNegPow2x.h
  asafov.andrew/P2/main.cpp
  asafov.andrew/P2/output.cpp
  asafov.andrew/P2/output.h
Labels: fine, gr 4

#124 karnauhova.alexandra/p3
  karnauhova.alexandra/P3/incomplete_matrix.cpp
  karnauhova.alexandra/P3/incomplete_matrix.hpp
  karnauhova.alexandra/P3/input_output.cpp
  karnauhova.alexandra/P3/input_output.hpp
  karnauhova.alexandra/P3/main.cpp
Labels: fine, gr 5

#136 kizhin.evgeniy/P3
  kizhin.evgeniy/P3/main.cpp
  kizhin.evgeniy/P3/matrix_utils.cpp
  kizhin.evgeniy/P3/matrix_utils.hpp
  kizhin.evgeniy/P3/memory_utils.hpp
  kizhin.evgeniy/P3/parse_arguments.cpp
  kizhin.evgeniy/P3/parse_arguments.hpp
Labels: fine, gr 5

#106 zholobov.oleg/P3
  zholobov.oleg/P3/main.cpp
  zholobov.oleg/P3/min_sum_mdg.cpp
  zholobov.oleg/P3/min_sum_mdg.hpp
Labels: fine, gr 5

#130 petrov.nikita/P3
  petrov.nikita/P3/count_not_zero_diagonals.cpp
  petrov.nikita/P3/input_matrix.cpp
  petrov.nikita/P3/main.cpp
  petrov.nikita/P3/process_the_matrix.hpp
Labels: fine, gr 1

#135 Brevnov.nikita/p3
  brevnov.nikita/P3/find_saddle_number.cpp
  brevnov.nikita/P3/find_saddle_number.hpp
  brevnov.nikita/P3/fll_inc_wav.cpp
  brevnov.nikita/P3/fll_inc_wav.hpp
  brevnov.nikita/P3/input_output_matrix.cpp
  brevnov.nikita/P3/input_output_matrix.hpp
  brevnov.nikita/P3/main.cpp
Labels: fine, gr 5

#117 aleksandrov.igor/P3
  aleksandrov.igor/P3/main.cpp
  aleksandrov.igor/P3/matrix.cpp
  aleksandrov.igor/P3/matrix.h
  aleksandrov.igor/P3/periphery.cpp
  aleksandrov.igor/P3/periphery.h
Labels: fine, gr 4

#116 shramko.maksim/P3
  shramko.maksim/P3/countColoumnsWithNonRepeatingNumbers.cpp
  shramko.maksim/P3/countColoumnsWithNonRepeatingNumbers.hpp
  shramko.maksim/P3/inputMtrx.cpp
  shramko.maksim/P3/inputMtrx.hpp
  shramko.maksim/P3/isNonRepeatingNumbers.hpp
  shramko.maksim/P3/main.cpp
Labels: fine, gr 1

#121 krylov.matvey/P3
  krylov.matvey/P3/main.cpp
  krylov.matvey/P3/matrixProcessing.cpp
  krylov.matvey/P3/matrixProcessing.hpp
Labels: fine, gr 4

#114 duhanina.alina/P3
  duhanina.alina/P3/inputMatrix.cpp
  duhanina.alina/P3/inputMtx.h
  duhanina.alina/P3/main.cpp
  duhanina.alina/P3/minSumMdg.cpp
  duhanina.alina/P3/minSumMdg.h
Labels: fine, gr 5

#102 abramov.vladislav/P3
  abramov.vladislav/P3/main.cpp
  abramov.vladislav/P3/matrix.cpp
  abramov.vladislav/P3/matrix.hpp
Labels: fine, gr 4

#113 mozhegova.maria/P3
  mozhegova.maria/P3/main.cpp
  mozhegova.maria/P3/matrix.cpp
  mozhegova.maria/P3/matrix.hpp
Labels: fine, gr 1

#103 finaev.alexey/P3
  finaev.alexey/P3/input_matrix.cpp
  finaev.alexey/P3/input_matrix.h
  finaev.alexey/P3/main.cpp
  finaev.alexey/P3/quantity_loc_max.cpp
  finaev.alexey/P3/quantity_loc_max.h
Labels: fine, gr 1

#133 guseynov.guseyn/P3
  guseynov.guseyn/P3/main.cpp
  guseynov.guseyn/P3/matrix.cpp
  guseynov.guseyn/P3/matrix.hpp
Labels: fine, gr 1

#123 hismatova.elizaveta/P3
  hismatova.elizaveta/P3/main.cpp
  hismatova.elizaveta/P3/matrix.cpp
  hismatova.elizaveta/P3/matrix.h
Labels: fine, gr 1

#144 Zakirov.marat/p3
  zakirov.marat/P3/main.cpp
  zakirov.marat/P3/mtx_work.cpp
  zakirov.marat/P3/mtx_work.hpp
Labels: fine, gr 4

#141 Balashov.dima/p3
  balashov.dima/P3/main.cpp
  balashov.dima/P3/matrixProcessing.cpp
  balashov.dima/P3/matrixProcessing.hpp
  balashov.dima/P3/stream.cpp
  balashov.dima/P3/stream.hpp
Labels: fine, gr 1

#137 sveshnikov.michail/P3
  sveshnikov.michail/P3/cnt_nzr_dig.cpp
  sveshnikov.michail/P3/cnt_nzr_dig.hpp
  sveshnikov.michail/P3/main.cpp
  sveshnikov.michail/P3/read_matrix.cpp
Labels: fine, gr 4

#132 sharifullina.sofia/p2
  sharifullina.sofia/P2/cos_expnegx.cpp
  sharifullina.sofia/P2/cos_expnegx.hpp
  sharifullina.sofia/P2/main.cpp
  sharifullina.sofia/P2/output.cpp
  sharifullina.sofia/P2/output.hpp
Labels: fine, gr 1

#157 maslevtsov.stanislav/P4
  maslevtsov.stanislav/P4/main.cpp
  maslevtsov.stanislav/P4/string_processing.cpp
  maslevtsov.stanislav/P4/string_processing.hpp
Labels: fine, gr 4

#165 Kiselev.sergey/p4
  kiselev.sergey/P4/identicalChar.cpp
  kiselev.sergey/P4/identicalChar.h
  kiselev.sergey/P4/main.cpp
  kiselev.sergey/common/inputString.cpp
  kiselev.sergey/common/inputString.h
Labels: fine, gr 5

#150 savintsev.ilya/p4
  savintsev.ilya/P4/dynamicstrings.cpp
  savintsev.ilya/P4/dynamicstrings.h
  savintsev.ilya/P4/main.cpp
  savintsev.ilya/common/newlineterminatedstr.cpp
  savintsev.ilya/common/newlineterminatedstr.h
Labels: fine, gr 4

#170 Brevnov.nikita/P4
  brevnov.nikita/P4/finding_common_elements.cpp
  brevnov.nikita/P4/finding_common_elements.hpp
  brevnov.nikita/P4/getline.cpp
  brevnov.nikita/P4/getline.hpp
  brevnov.nikita/P4/main.cpp
Labels: fine, gr 5

#164 mozhegova.maria/P4
  mozhegova.maria/P4/main.cpp
  mozhegova.maria/P4/strmanipulator.cpp
  mozhegova.maria/P4/strmanipulator.hpp
Labels: fine, gr 1

#149 alymova.ksenia/P4
  alymova.ksenia/P4/main.cpp
  alymova.ksenia/P4/reform.cpp
  alymova.ksenia/P4/reform.h
  alymova.ksenia/common/dynamic_string.cpp
  alymova.ksenia/common/dynamic_string.h
Labels: fine, gr 4

#104 maslovskiy.vladislav/P3
  maslovskiy.vladislav/P3/countInMtx.cpp
  maslovskiy.vladislav/P3/countInMtx.hpp
  maslovskiy.vladislav/P3/hasDuplicatesInColumn.cpp
  maslovskiy.vladislav/P3/hasDuplicatesInColumn.hpp
  maslovskiy.vladislav/P3/inputMatrix.cpp
  maslovskiy.vladislav/P3/inputMatrix.hpp
  maslovskiy.vladislav/P3/main.cpp
Labels: fine, gr 4

#167 karnauhova.alexandra/p4
  karnauhova.alexandra/P4/dubl_char.cpp
  karnauhova.alexandra/P4/dubl_char.hpp
  karnauhova.alexandra/P4/main.cpp
  karnauhova.alexandra/common/input_string.cpp
  karnauhova.alexandra/common/input_string.hpp
Labels: fine, gr 5

#161 tkach.danil/P4
  tkach.danil/P4/getmemoryforstr.cpp
  tkach.danil/P4/inputstr.cpp
  tkach.danil/P4/main.cpp
  tkach.danil/P4/removevowels.cpp
  tkach.danil/P4/removevowels.h
  tkach.danil/P4/stringinput.h
Labels: fine, gr 1

#152 finaev.alexey/P4
  finaev.alexey/P4/is_repeat.cpp
  finaev.alexey/P4/main.cpp
  finaev.alexey/P4/string_conversion.h
  finaev.alexey/common/create_str.cpp
  finaev.alexey/common/create_str.h
Labels: fine, gr 1

#147 smirnov.alexandr/P3
  smirnov.alexandr/P3/main.cpp
  smirnov.alexandr/P3/matrix.cpp
  smirnov.alexandr/P3/matrix.hpp
Labels: fine, gr 1

#156 aleksandrov.igor/P4
  aleksandrov.igor/P4/getString.cpp
  aleksandrov.igor/P4/getString.h
  aleksandrov.igor/P4/latinRemove.cpp
  aleksandrov.igor/P4/latinRemove.h
  aleksandrov.igor/P4/main.cpp
Labels: fine, gr 4

#213 maslov.aleksey/P6
  maslov.aleksey/P4/main.cpp
  maslov.aleksey/P4/stringManipulator.cpp
  maslov.aleksey/P4/stringManipulator.hpp
  maslov.aleksey/P6/grammarChecker.cpp
  maslov.aleksey/P6/grammarChecker.hpp
  maslov.aleksey/P6/main.cpp
  maslov.aleksey/common/stringInput.cpp
  maslov.aleksey/common/stringInput.hpp
Labels: fine, gr 1

#186 Balashov.dima/p4
  balashov.dima/P4/main.cpp
  balashov.dima/P4/processingString.cpp
  balashov.dima/P4/processingString.hpp
Labels: fine, gr 1

#178 zholobov.oleg/P4
  zholobov.oleg/P4/exc_snd.cpp
  zholobov.oleg/P4/exc_snd.hpp
  zholobov.oleg/P4/main.cpp
Labels: fine, gr 5

#212 finaev.alexey/P6
  finaev.alexey/P6/check_str.cpp
  finaev.alexey/P6/check_str.h
  finaev.alexey/P6/main.cpp
Labels: fine, gr 1

#196 timofeev.maxim/P3
  timofeev.maxim/P3/cut_to_square.cpp
  timofeev.maxim/P3/cut_to_square.h
  timofeev.maxim/P3/input_matrix.cpp
  timofeev.maxim/P3/input_matrix.h
  timofeev.maxim/P3/main.cpp
  timofeev.maxim/P3/output_matrix.cpp
  timofeev.maxim/P3/output_matrix.h
Labels: fine, gr 1, minus 1

#199 alymova.ksenia/P6
  alymova.ksenia/P6/main.cpp
  alymova.ksenia/P6/recursion_string.cpp
  alymova.ksenia/P6/recursion_string.h
Labels: fine, gr 4

#214 tkach.danil/P6
  tkach.danil/P4/main.cpp
  tkach.danil/P6/isexpression.cpp
  tkach.danil/P6/isexpression.h
  tkach.danil/P6/main.cpp
  tkach.danil/common/getmemoryforstr.cpp
  tkach.danil/common/inputstr.cpp
  tkach.danil/common/stringinput.hpp
Labels: fine, gr 1

#172 duhanina.alina/P4
  duhanina.alina/P4/main.cpp
  duhanina.alina/P4/shrSym.cpp
  duhanina.alina/P4/shrSym.h
  duhanina.alina/common/inputStr.cpp
  duhanina.alina/common/inputStr.h
Labels: fine, gr 5

#155 demehin.maxim/P4
  demehin.maxim/P4/main.cpp
  demehin.maxim/P4/unc_sym.cpp
  demehin.maxim/P4/unc_sym.h
  demehin.maxim/common/string_utils.cpp
  demehin.maxim/common/string_utils.h
Labels: fine, gr 5

#169 sveshnikov.michail/P4
  sveshnikov.michail/P4/main.cpp
  sveshnikov.michail/P4/rep_sym.cpp
  sveshnikov.michail/P4/search_repeats.hpp
  sveshnikov.michail/common/getline.hpp
  sveshnikov.michail/common/memory_alloc.cpp
  sveshnikov.michail/common/read_str.cpp
Labels: fine, gr 4

#159 abramov.vladislav/P4
  abramov.vladislav/P4/main.cpp
  abramov.vladislav/P4/unionStrs.cpp
  abramov.vladislav/P4/unionStrs.hpp
  abramov.vladislav/common/getString.cpp
  abramov.vladislav/common/getString.hpp
Labels: fine, gr 4

#202 kizhin.evgeniy/P6
  kizhin.evgeniy/P6/is_expression.cpp
  kizhin.evgeniy/P6/is_expression.hpp
  kizhin.evgeniy/P6/main.cpp
Labels: fine, gr 5

#218 karnauhova.alexandra/p6
  karnauhova.alexandra/P6/check_real.cpp
  karnauhova.alexandra/P6/check_real.hpp
  karnauhova.alexandra/P6/main.cpp
  karnauhova.alexandra/common/input_string.cpp
Labels: fine, gr 5
