Repository Volgarenok/spbspu-labs-2024-aap-a, pull requests merged in 2025-03, with the labels that each got.

#246 finaev.alexey/T1
  finaev.alexey/T1/base-types.hpp
  finaev.alexey/T1/concave.cpp
  finaev.alexey/T1/concave.hpp
  finaev.alexey/T1/countFinalResults.cpp
  finaev.alexey/T1/countFinalResults.hpp
  finaev.alexey/T1/deleteShapes.cpp
  finaev.alexey/T1/main.cpp
  finaev.alexey/T1/makeShapes.cpp
  finaev.alexey/T1/makeShapes.hpp
  finaev.alexey/T1/rectangle.cpp
  finaev.alexey/T1/rectangle.hpp
  finaev.alexey/T1/scale.cpp
  finaev.alexey/T1/scale.hpp
  finaev.alexey/T1/shape.hpp
  finaev.alexey/T1/square.cpp
  finaev.alexey/T1/square.hpp
Labels: fine, gr 1, 7 out of 12

#267 asafov.andrew/T1
  asafov.andrew/T1/base-types.hpp
  asafov.andrew/T1/circle.cpp
  asafov.andrew/T1/circle.hpp
  asafov.andrew/T1/complexquad.cpp
  asafov.andrew/T1/complexquad.hpp
  asafov.andrew/T1/ellipse.cpp
  asafov.andrew/T1/ellipse.hpp
  asafov.andrew/T1/main.cpp
  asafov.andrew/T1/outputFunctions.cpp
  asafov.andrew/T1/outputFunctions.hpp
  asafov.andrew/T1/rectangle.cpp
  asafov.andrew/T1/rectangle.hpp
  asafov.andrew/T1/ring.cpp
  asafov.andrew/T1/ring.hpp
  asafov.andrew/T1/shape.cpp
  asafov.andrew/T1/shape.hpp
  asafov.andrew/T1/square.cpp
  asafov.andrew/T1/square.hpp
  asafov.andrew/T1/supportFunctions.cpp
  asafov.andrew/T1/supportFunctions.hpp
  asafov.andrew/T1/triangle.cpp
  asafov.andrew/T1/triangle.hpp
Labels: fine, gr 4, 7 out of 12, 4 out of 12

#260 lanovenko.ivan/T1
  lanovenko.ivan/T1/base-types.hpp
  lanovenko.ivan/T1/delete_shape.cpp
  lanovenko.ivan/T1/delete_shape.hpp
  lanovenko.ivan/T1/diamond.cpp
  lanovenko.ivan/T1/diamond.hpp
  lanovenko.ivan/T1/main.cpp
  lanovenko.ivan/T1/parallelogram.cpp
  lanovenko.ivan/T1/parallelogram.hpp
  lanovenko.ivan/T1/rectangle.cpp
  lanovenko.ivan/T1/rectangle.hpp
  lanovenko.ivan/T1/scale_functions.cpp
  lanovenko.ivan/T1/scale_functions.hpp
  lanovenko.ivan/T1/shape.cpp
  lanovenko.ivan/T1/shape.hpp
  lanovenko.ivan/T1/string_manipulations.cpp
  lanovenko.ivan/T1/string_manipulations.hpp
  lanovenko.ivan/T1/triangle.cpp
  lanovenko.ivan/T1/triangle.hpp
  lanovenko.ivan/common/strinput.cpp
  lanovenko.ivan/common/strinput.h
Labels: fine, gr 1, 7 out of 12

#301 Beshimow.meylis/p3
  beshimow.meylis/P3/main.cpp
  beshimow.meylis/P3/matrix.cpp
  beshimow.meylis/P3/matrix.hpp
Labels: fine, gr 5, minus 3

#308 Kalmbah.mihail/p2
  kalmbah.mihail/P2/compute_hyperbol_functions.cpp
  kalmbah.mihail/P2/compute_hyperbol_functions.h
  kalmbah.mihail/P2/main.cpp
Labels: gr 4, minus 3

#307 dirti.aldyn/T1
  dirti.aldyn/T1/base-types.hpp
  dirti.aldyn/T1/inputFigures.cpp
  dirti.aldyn/T1/inputFigures.hpp
  dirti.aldyn/T1/main.cpp
  dirti.aldyn/T1/outputFigures.cpp
  dirti.aldyn/T1/outputFigures.hpp
  dirti.aldyn/T1/parallelogram.cpp
  dirti.aldyn/T1/parallelogram.hpp
  dirti.aldyn/T1/rectangle.cpp
  dirti.aldyn/T1/rectangle.hpp
  dirti.aldyn/T1/shape.cpp
  dirti.aldyn/T1/shape.hpp
  dirti.aldyn/T1/square.cpp
  dirti.aldyn/T1/square.hpp
Labels: fine, gr 5, 7 out of 12

#244 lebedev.alexandr/T1
  lebedev.alexandr/T1/actionsWithShapes.cpp
  lebedev.alexandr/T1/actionsWithShapes.hpp
  lebedev.alexandr/T1/base-types.hpp
  lebedev.alexandr/T1/concave.cpp
  lebedev.alexandr/T1/concave.hpp
  lebedev.alexandr/T1/createShapes.cpp
  lebedev.alexandr/T1/createShapes.hpp
  lebedev.alexandr/T1/diamond.cpp
  lebedev.alexandr/T1/diamond.hpp
  lebedev.alexandr/T1/main.cpp
  lebedev.alexandr/T1/rectangle.cpp
  lebedev.alexandr/T1/rectangle.hpp
  lebedev.alexandr/T1/shape.hpp
  lebedev.alexandr/T1/triangleOperations.cpp
  lebedev.alexandr/T1/triangleOperations.hpp
Labels: fine, gr 1, 7 out of 12
