Repository Volgarenok/spbspu-labs-2024-aap-a, pull requests merged in 2025-01, with the labels that each got.

#283 komarova.anastasia/P6
  komarova.anastasia/P4/main.cpp
  komarova.anastasia/P6/main.cpp
  komarova.anastasia/P6/recursion_float.cpp
  komarova.anastasia/P6/recursion_float.h
  komarova.anastasia/common/dynamic.cpp
  komarova.anastasia/common/dynamic.h
Labels: fine, gr 4

#277 sharifullina.sofia/P6
  sharifullina.sofia/P6/isExpression.cpp
  sharifullina.sofia/P6/isExpression.hpp
  sharifullina.sofia/P6/main.cpp
  sharifullina.sofia/common/inputString.cpp
  sharifullina.sofia/common/inputString.hpp
Labels: fine, gr 1

#238 demehin.maxim/T1
  demehin.maxim/T1/base-types.hpp
  demehin.maxim/T1/creating_utils.cpp
  demehin.maxim/T1/creating_utils.hpp
  demehin.maxim/T1/factory.cpp
  demehin.maxim/T1/factory.hpp
  demehin.maxim/T1/main.cpp
  demehin.maxim/T1/polygon.cpp
  demehin.maxim/T1/polygon.hpp
  demehin.maxim/T1/rectangle.cpp
  demehin.maxim/T1/rectangle.hpp
  demehin.maxim/T1/ring.cpp
  demehin.maxim/T1/ring.hpp
  demehin.maxim/T1/shape.cpp
  demehin.maxim/T1/shape.hpp
Labels: fine, gr 5, 7 out of 12
