Repository Volgarenok/spbspu-labs-2024-aap-a, pull requests merged in 2025-02, with the labels that each got.

#235 savintsev.ilya/T1
  savintsev.ilya/T1/base-types.hpp
  savintsev.ilya/T1/complexquad.cpp
  savintsev.ilya/T1/complexquad.hpp
  savintsev.ilya/T1/composite-shape.cpp
  savintsev.ilya/T1/composite-shape.hpp
  savintsev.ilya/T1/concave.cpp
  savintsev.ilya/T1/concave.hpp
  savintsev.ilya/T1/geometry-utils.cpp
  savintsev.ilya/T1/geometry-utils.hpp
  savintsev.ilya/T1/main.cpp
  savintsev.ilya/T1/rectangle.cpp
  savintsev.ilya/T1/rectangle.hpp
  savintsev.ilya/T1/shape-utils.cpp
  savintsev.ilya/T1/shape-utils.hpp
  savintsev.ilya/T1/shape.cpp
  savintsev.ilya/T1/shape.hpp
  savintsev.ilya/common/lrgcpy.hpp
  savintsev.ilya/common/newlineterminatedstr.cpp
  savintsev.ilya/common/newlineterminatedstr.h
Labels: fine, gr 4, 12 out of 12

#253 duhanina.alina/T1
  duhanina.alina/T1/base-types.hpp
  duhanina.alina/T1/circle.cpp
  duhanina.alina/T1/circle.hpp
  duhanina.alina/T1/createCommand.cpp
  duhanina.alina/T1/createCommand.hpp
  duhanina.alina/T1/destroy.cpp
  duhanina.alina/T1/destroy.hpp
  duhanina.alina/T1/ellipse.cpp
  duhanina.alina/T1/ellipse.hpp
  duhanina.alina/T1/main.cpp
  duhanina.alina/T1/movingPoint.cpp
  duhanina.alina/T1/movingPoint.hpp
  duhanina.alina/T1/printResult.cpp
  duhanina.alina/T1/printResult.hpp
  duhanina.alina/T1/rectangle.cpp
  duhanina.alina/T1/rectangle.hpp
  duhanina.alina/T1/shape.cpp
  duhanina.alina/T1/shape.hpp
Labels: fine, gr 5, Смешарик, 7 out of 12

#259 mozhegova.maria/T1
  mozhegova.maria/T1/base-types.hpp
  mozhegova.maria/T1/diamond.cpp
  mozhegova.maria/T1/diamond.hpp
  mozhegova.maria/T1/main.cpp
  mozhegova.maria/T1/makeShape.cpp
  mozhegova.maria/T1/makeShape.hpp
  mozhegova.maria/T1/polygon.cpp
  mozhegova.maria/T1/polygon.hpp
  mozhegova.maria/T1/rectangle.cpp
  mozhegova.maria/T1/rectangle.hpp
  mozhegova.maria/T1/shape.cpp
  mozhegova.maria/T1/shape.hpp
  mozhegova.maria/T1/shapeManipulator.cpp
  mozhegova.maria/T1/shapeManipulator.hpp
Labels: fine, gr 1, 7 out of 12

#221 dirti.aldyn/P3
  dirti.aldyn/P3/input_matrix.cpp
  dirti.aldyn/P3/local_min.cpp
  dirti.aldyn/P3/main.cpp
  dirti.aldyn/P3/matrix_checking.cpp
  dirti.aldyn/P3/matrix_functions.hpp
Labels: fine, trash, gr 5, minus 3

#248 kizhin.evgeniy/T1
  kizhin.evgeniy/T1/base-types.hpp
  kizhin.evgeniy/T1/composite_shape.cpp
  kizhin.evgeniy/T1/composite_shape.hpp
  kizhin.evgeniy/T1/io_utils.cpp
  kizhin.evgeniy/T1/io_utils.hpp
  kizhin.evgeniy/T1/main.cpp
  kizhin.evgeniy/T1/point_utils.cpp
  kizhin.evgeniy/T1/point_utils.hpp
  kizhin.evgeniy/T1/polygon.cpp
  kizhin.evgeniy/T1/polygon.hpp
  kizhin.evgeniy/T1/rectangle.cpp
  kizhin.evgeniy/T1/rectangle.hpp
  kizhin.evgeniy/T1/regular.cpp
  kizhin.evgeniy/T1/regular.hpp
  kizhin.evgeniy/T1/shape.cpp
  kizhin.evgeniy/T1/shape.hpp
  kizhin.evgeniy/T1/shape_utils.cpp
  kizhin.evgeniy/T1/shape_utils.hpp
Labels: fine, gr 5, 12 out of 12

#257 timofeev.maxim/T1
  timofeev.maxim/T1/base-types.hpp
  timofeev.maxim/T1/complexquad.cpp
  timofeev.maxim/T1/complexquad.hpp
  timofeev.maxim/T1/concave.cpp
  timofeev.maxim/T1/concave.hpp
  timofeev.maxim/T1/main.cpp
  timofeev.maxim/T1/rectangle.cpp
  timofeev.maxim/T1/rectangle.hpp
  timofeev.maxim/T1/shape.hpp
  timofeev.maxim/T1/shapes_tools.cpp
  timofeev.maxim/T1/shapes_tools.hpp
  timofeev.maxim/T1/triangle.cpp
  timofeev.maxim/T1/triangle.hpp
Labels: fine, trash, gr 1, 5 out of 12

#271 rychkov.mihail/T1
  rychkov.mihail/T1/base-types.cpp
  rychkov.mihail/T1/base-types.hpp
  rychkov.mihail/T1/composite-shape.cpp
  rychkov.mihail/T1/composite-shape.hpp
  rychkov.mihail/T1/main.cpp
  rychkov.mihail/T1/polygon.cpp
  rychkov.mihail/T1/polygon.hpp
  rychkov.mihail/T1/rectangle.cpp
  rychkov.mihail/T1/rectangle.hpp
  rychkov.mihail/T1/regular.cpp
  rychkov.mihail/T1/regular.hpp
  rychkov.mihail/T1/shape.cpp
  rychkov.mihail/T1/shape.hpp
  rychkov.mihail/T1/shapes_input.cpp
  rychkov.mihail/T1/shapes_input.hpp
  rychkov.mihail/common/math.cpp
  rychkov.mihail/common/math.hpp
  rychkov.mihail/common/string_comparison.cpp
  rychkov.mihail/common/string_comparison.hpp
Labels: fine, gr 1, 12 out of 12

#266 petrov.nikita/T1
  petrov.nikita/T1/base-types.hpp
  petrov.nikita/T1/composite-shape.cpp
  petrov.nikita/T1/composite-shape.hpp
  petrov.nikita/T1/concave.cpp
  petrov.nikita/T1/concave.hpp
  petrov.nikita/T1/geometric_calculations.cpp
  petrov.nikita/T1/geometric_calculations.hpp
  petrov.nikita/T1/input_cstring_until_ws.cpp
  petrov.nikita/T1/input_cstring_until_ws.hpp
  petrov.nikita/T1/main.cpp
  petrov.nikita/T1/make_shape.cpp
  petrov.nikita/T1/make_shape.hpp
  petrov.nikita/T1/rectangle.cpp
  petrov.nikita/T1/rectangle.hpp
  petrov.nikita/T1/scale_isotropically_and_output_data.cpp
  petrov.nikita/T1/scale_isotropically_and_output_data.hpp
  petrov.nikita/T1/shape.hpp
  petrov.nikita/T1/triangle.cpp
  petrov.nikita/T1/triangle.hpp
Labels: fine, gr 1, 12 out of 12

#249 nikonov.andrew/T1
  nikonov.andrew/T1/additional-utilities.cpp
  nikonov.andrew/T1/additional-utilities.hpp
  nikonov.andrew/T1/base-types.cpp
  nikonov.andrew/T1/base-types.hpp
  nikonov.andrew/T1/composite-shape.cpp
  nikonov.andrew/T1/composite-shape.hpp
  nikonov.andrew/T1/diamond.cpp
  nikonov.andrew/T1/diamond.hpp
  nikonov.andrew/T1/fabric.cpp
  nikonov.andrew/T1/fabric.hpp
  nikonov.andrew/T1/main.cpp
  nikonov.andrew/T1/rectangle.cpp
  nikonov.andrew/T1/rectangle.hpp
  nikonov.andrew/T1/shape.cpp
  nikonov.andrew/T1/shape.hpp
  nikonov.andrew/T1/triangle.cpp
  nikonov.andrew/T1/triangle.hpp
Labels: fine, gr 4, Смешарик, 10 out of 12

#256 tkach.danil/T1
  tkach.danil/T1/base-types.cpp
  tkach.danil/T1/base-types.hpp
  tkach.danil/T1/composite-shape.cpp
  tkach.danil/T1/composite-shape.hpp
  tkach.danil/T1/figureactions.cpp
  tkach.danil/T1/figureactions.hpp
  tkach.danil/T1/main.cpp
  tkach.danil/T1/makeshapes.cpp
  tkach.danil/T1/makeshapes.hpp
  tkach.danil/T1/rectangle.cpp
  tkach.danil/T1/rectangle.hpp
  tkach.danil/T1/regular.cpp
  tkach.danil/T1/regular.hpp
  tkach.danil/T1/ring.cpp
  tkach.danil/T1/ring.hpp
  tkach.danil/T1/shape.cpp
  tkach.danil/T1/shape.hpp
Labels: fine, gr 1, 12 out of 12

#240 kiselev.sergey/T1
  kiselev.sergey/T1/actionShapes.cpp
  kiselev.sergey/T1/actionShapes.hpp
  kiselev.sergey/T1/base-types.cpp
  kiselev.sergey/T1/base-types.hpp
  kiselev.sergey/T1/complexquad.cpp
  kiselev.sergey/T1/complexquad.hpp
  kiselev.sergey/T1/composite-shape.cpp
  kiselev.sergey/T1/composite-shape.hpp
  kiselev.sergey/T1/diamond.cpp
  kiselev.sergey/T1/diamond.hpp
  kiselev.sergey/T1/main.cpp
  kiselev.sergey/T1/makeShapes.cpp
  kiselev.sergey/T1/makeShapes.hpp
  kiselev.sergey/T1/rectangle.cpp
  kiselev.sergey/T1/rectangle.hpp
  kiselev.sergey/T1/shape.cpp
  kiselev.sergey/T1/shape.hpp
Labels: fine, gr 5, 12 out of 12

#272 hismatova.elizaveta/T1
  hismatova.elizaveta/T1/base-types.hpp
  hismatova.elizaveta/T1/concave.cpp
  hismatova.elizaveta/T1/concave.hpp
  hismatova.elizaveta/T1/createFigure.cpp
  hismatova.elizaveta/T1/createFigure.hpp
  hismatova.elizaveta/T1/main.cpp
  hismatova.elizaveta/T1/rectangle.cpp
  hismatova.elizaveta/T1/rectangle.hpp
  hismatova.elizaveta/T1/shape.cpp
  hismatova.elizaveta/T1/shape.hpp
  hismatova.elizaveta/T1/triangle.cpp
  hismatova.elizaveta/T1/triangle.hpp
Labels: fine, gr 1, 5 out of 12

#243 averenkov.eugene/T1
  averenkov.eugene/T1/base-types.hpp
  averenkov.eugene/T1/diamond.cpp
  averenkov.eugene/T1/diamond.hpp
  averenkov.eugene/T1/ellipse.cpp
  averenkov.eugene/T1/ellipse.hpp
  averenkov.eugene/T1/listCommand.cpp
  averenkov.eugene/T1/listCommand.hpp
  averenkov.eugene/T1/main.cpp
  averenkov.eugene/T1/makeshape.cpp
  averenkov.eugene/T1/makeshape.hpp
  averenkov.eugene/T1/rectangle.cpp
  averenkov.eugene/T1/rectangle.hpp
  averenkov.eugene/T1/shape.cpp
  averenkov.eugene/T1/shape.hpp
Labels: fine, gr 5, 7 out of 12

#179 belobrov.timofey/P4
  belobrov.timofey/P4/inputString.cpp
  belobrov.timofey/P4/inputString.hpp
  belobrov.timofey/P4/main.cpp
  belobrov.timofey/P4/replaceChars.cpp
  belobrov.timofey/P4/replaceChars.hpp
Labels: fine, gr 4, minus 2

#258 maslov.aleksey/T1
  maslov.aleksey/T1/base-types.cpp
  maslov.aleksey/T1/base-types.hpp
  maslov.aleksey/T1/composite-shape.cpp
  maslov.aleksey/T1/composite-shape.hpp
  maslov.aleksey/T1/inputShape.cpp
  maslov.aleksey/T1/inputShape.hpp
  maslov.aleksey/T1/main.cpp
  maslov.aleksey/T1/parallelogram.cpp
  maslov.aleksey/T1/parallelogram.hpp
  maslov.aleksey/T1/rectangle.cpp
  maslov.aleksey/T1/rectangle.hpp
  maslov.aleksey/T1/regular.cpp
  maslov.aleksey/T1/regular.hpp
  maslov.aleksey/T1/shape.cpp
  maslov.aleksey/T1/shape.hpp
  maslov.aleksey/T1/shapeManipulator.cpp
  maslov.aleksey/T1/shapeManipulator.hpp
Labels: fine, gr 1, 10 out of 12

#265 maslevtsov.stanislav/T1
  maslevtsov.stanislav/T1/base-types.hpp
  maslevtsov.stanislav/T1/getline_string_to_doubles.cpp
  maslevtsov.stanislav/T1/getline_string_to_doubles.hpp
  maslevtsov.stanislav/T1/main.cpp
  maslevtsov.stanislav/T1/polygon.cpp
  maslevtsov.stanislav/T1/polygon.hpp
  maslevtsov.stanislav/T1/rectangle.cpp
  maslevtsov.stanislav/T1/rectangle.hpp
  maslevtsov.stanislav/T1/regular.cpp
  maslevtsov.stanislav/T1/regular.hpp
  maslevtsov.stanislav/T1/shape.cpp
  maslevtsov.stanislav/T1/shape.hpp
Labels: fine, gr 4, hall of legends, 7 out of 12

#263 karnauhova.alexandra/T1
  karnauhova.alexandra/T1/base-types.hpp
  karnauhova.alexandra/T1/compositeShape.cpp
  karnauhova.alexandra/T1/compositeShape.hpp
  karnauhova.alexandra/T1/input.cpp
  karnauhova.alexandra/T1/input.hpp
  karnauhova.alexandra/T1/main.cpp
  karnauhova.alexandra/T1/output.cpp
  karnauhova.alexandra/T1/output.hpp
  karnauhova.alexandra/T1/point.cpp
  karnauhova.alexandra/T1/point.hpp
  karnauhova.alexandra/T1/polygon.cpp
  karnauhova.alexandra/T1/polygon.hpp
  karnauhova.alexandra/T1/rectangle.cpp
  karnauhova.alexandra/T1/rectangle.hpp
  karnauhova.alexandra/T1/shape.cpp
  karnauhova.alexandra/T1/shape.hpp
  karnauhova.alexandra/T1/triangle.cpp
  karnauhova.alexandra/T1/triangle.hpp
Labels: fine, gr 5, 12 out of 12

#181 asafov.andrew/P4
  asafov.andrew/P4/main.cpp
  asafov.andrew/P4/stringFunctions.cpp
  asafov.andrew/P4/stringFunctions.hpp
  asafov.andrew/common/inputString.cpp
  asafov.andrew/common/inputString.hpp
  asafov.andrew/common/resize.cpp
  asafov.andrew/common/resize.hpp
Labels: fine, gr 4, minus 2

#262 zholobov.oleg/T1
  zholobov.oleg/P3/min_sum_mdg.cpp
  zholobov.oleg/T1/base-types.hpp
  zholobov.oleg/T1/composite-shape.cpp
  zholobov.oleg/T1/composite-shape.hpp
  zholobov.oleg/T1/main.cpp
  zholobov.oleg/T1/parallelogram.cpp
  zholobov.oleg/T1/parallelogram.hpp
  zholobov.oleg/T1/rectangle.cpp
  zholobov.oleg/T1/rectangle.hpp
  zholobov.oleg/T1/shape.hpp
  zholobov.oleg/T1/shapes_utils.cpp
  zholobov.oleg/T1/shapes_utils.hpp
  zholobov.oleg/T1/square.cpp
  zholobov.oleg/T1/square.hpp
  zholobov.oleg/common/common_utils.hpp
Labels: fine, gr 5, hall of legends, 10 out of 12

#209 asafov.andrew/P6
  asafov.andrew/P6/isExpression.cpp
  asafov.andrew/P6/isExpression.hpp
  asafov.andrew/P6/main.cpp
Labels: fine, gr 4, minus 3

#247 abramov.vladislav/T1
  abramov.vladislav/T1/base-types.cpp
  abramov.vladislav/T1/base-types.hpp
  abramov.vladislav/T1/complexquad.cpp
  abramov.vladislav/T1/complexquad.hpp
  abramov.vladislav/T1/composite-shape.cpp
  abramov.vladislav/T1/composite-shape.hpp
  abramov.vladislav/T1/main.cpp
  abramov.vladislav/T1/rectangle.cpp
  abramov.vladislav/T1/rectangle.hpp
  abramov.vladislav/T1/shape.cpp
  abramov.vladislav/T1/shape.hpp
  abramov.vladislav/T1/shape_transformations.cpp
  abramov.vladislav/T1/shape_transformations.hpp
  abramov.vladislav/T1/square.cpp
  abramov.vladislav/T1/square.hpp
Labels: fine, gr 4, 12 out of 12

#254 zakirov.marat/T1
  zakirov.marat/P4/main.cpp
  zakirov.marat/P6/main.cpp
  zakirov.marat/T1/base-types.cpp
  zakirov.marat/T1/base-types.hpp
  zakirov.marat/T1/circle.cpp
  zakirov.marat/T1/circle.hpp
  zakirov.marat/T1/composite-shape.cpp
  zakirov.marat/T1/composite-shape.hpp
  zakirov.marat/T1/io_data.cpp
  zakirov.marat/T1/io_data.hpp
  zakirov.marat/T1/main.cpp
  zakirov.marat/T1/polygon.cpp
  zakirov.marat/T1/polygon.hpp
  zakirov.marat/T1/rectangle.cpp
  zakirov.marat/T1/rectangle.hpp
  zakirov.marat/T1/ring.cpp
  zakirov.marat/T1/ring.hpp
  zakirov.marat/T1/shape.cpp
  zakirov.marat/T1/shape.hpp
  zakirov.marat/T1/shape_factory.cpp
  zakirov.marat/T1/shape_factory.hpp
  zakirov.marat/common/resize_line.cpp
  zakirov.marat/common/resize_line.hpp
Labels: fine, gr 4, Смешарик, 10 out of 12, Кроршах

#250 gavrilova.polina/T1
  gavrilova.polina/P4/main.cpp
  gavrilova.polina/P6/main.cpp
  gavrilova.polina/T1/base-types.cpp
  gavrilova.polina/T1/base-types.hpp
  gavrilova.polina/T1/compositeShape.cpp
  gavrilova.polina/T1/compositeShape.hpp
  gavrilova.polina/T1/ellipse.cpp
  gavrilova.polina/T1/ellipse.hpp
  gavrilova.polina/T1/main.cpp
  gavrilova.polina/T1/make_shape.cpp
  gavrilova.polina/T1/make_shape.hpp
  gavrilova.polina/T1/pointManip.cpp
  gavrilova.polina/T1/pointManip.hpp
  gavrilova.polina/T1/polygon.cpp
  gavrilova.polina/T1/polygon.hpp
  gavrilova.polina/T1/rectangle.cpp
  gavrilova.polina/T1/rectangle.hpp
  gavrilova.polina/T1/shape.cpp
  gavrilova.polina/T1/shape.hpp
  gavrilova.polina/T1/shapeManip.cpp
  gavrilova.polina/T1/shapeManip.hpp
  gavrilova.polina/T1/triangle.cpp
  gavrilova.polina/T1/triangle.hpp
  gavrilova.polina/common/inputStr.cpp
  gavrilova.polina/common/inputStr.hpp
Labels: trash, black-mark, gr 5, Смешарик, 12 out of 12

#275 alymova.ksenia/T1
  alymova.ksenia/T1/base-types.cpp
  alymova.ksenia/T1/base-types.hpp
  alymova.ksenia/T1/circle.cpp
  alymova.ksenia/T1/circle.hpp
  alymova.ksenia/T1/composite-shape.cpp
  alymova.ksenia/T1/composite-shape.hpp
  alymova.ksenia/T1/fabrics.cpp
  alymova.ksenia/T1/fabrics.hpp
  alymova.ksenia/T1/inputProcess.cpp
  alymova.ksenia/T1/inputProcess.hpp
  alymova.ksenia/T1/main.cpp
  alymova.ksenia/T1/rectangle.cpp
  alymova.ksenia/T1/rectangle.hpp
  alymova.ksenia/T1/regular.cpp
  alymova.ksenia/T1/regular.hpp
  alymova.ksenia/T1/shape.cpp
  alymova.ksenia/T1/shape.hpp
Labels: fine, gr 4, 12 out of 12

#285 dirti.aldyn/P4
  dirti.aldyn/P4/findMin.cpp
  dirti.aldyn/P4/findMin.hpp
  dirti.aldyn/P4/findMinRecursed.cpp
  dirti.aldyn/P4/findMinRecursed.hpp
  dirti.aldyn/P4/findTwoMin.cpp
  dirti.aldyn/P4/findTwoMin.hpp
  dirti.aldyn/P4/main.cpp
  dirti.aldyn/common/inputStr.cpp
  dirti.aldyn/common/inputStr.hpp
Labels: fine, gr 5, minus 3

#305 kalmbah.mihail/P0
  kalmbah.mihail/P0/main.cpp
Labels: fine, gr 4

#242 Brevnov.nikita/T1
  brevnov.nikita/T1/base-types.hpp
  brevnov.nikita/T1/composite-shape.cpp
  brevnov.nikita/T1/composite-shape.hpp
  brevnov.nikita/T1/diamond.cpp
  brevnov.nikita/T1/diamond.hpp
  brevnov.nikita/T1/ellipse.cpp
  brevnov.nikita/T1/ellipse.hpp
  brevnov.nikita/T1/main.cpp
  brevnov.nikita/T1/makeShape.cpp
  brevnov.nikita/T1/makeShape.hpp
  brevnov.nikita/T1/rectangle.cpp
  brevnov.nikita/T1/rectangle.hpp
  brevnov.nikita/T1/shape.cpp
  brevnov.nikita/T1/shape.hpp
Labels: fine, gr 5, 12 out of 12

#278 sveshnikov.michail/T1
  sveshnikov.michail/T1/base-types.cpp
  sveshnikov.michail/T1/base-types.hpp
  sveshnikov.michail/T1/build_shapes.cpp
  sveshnikov.michail/T1/build_shapes.hpp
  sveshnikov.michail/T1/composite-shape.cpp
  sveshnikov.michail/T1/composite-shape.hpp
  sveshnikov.michail/T1/ellipse.cpp
  sveshnikov.michail/T1/ellipse.hpp
  sveshnikov.michail/T1/main.cpp
  sveshnikov.michail/T1/rectangle.cpp
  sveshnikov.michail/T1/rectangle.hpp
  sveshnikov.michail/T1/ring.cpp
  sveshnikov.michail/T1/ring.hpp
  sveshnikov.michail/T1/shape.cpp
  sveshnikov.michail/T1/shape.hpp
  sveshnikov.michail/T1/shape_actions.cpp
  sveshnikov.michail/T1/shape_actions.hpp
  sveshnikov.michail/T1/square.cpp
  sveshnikov.michail/T1/square.hpp
Labels: fine, gr 4, 10 out of 12

#288 dirti.aldyn/P6
  dirti.aldyn/P6/is_expression.cpp
  dirti.aldyn/P6/is_expression.hpp
  dirti.aldyn/P6/main.cpp
Labels: fine, gr 5, minus 3

#280 Bocharov.egor/T1
  bocharov.egor/T1/base-types.cpp
  bocharov.egor/T1/base-types.hpp
  bocharov.egor/T1/concave.cpp
  bocharov.egor/T1/concave.hpp
  bocharov.egor/T1/getShapeInfo.cpp
  bocharov.egor/T1/getShapeInfo.hpp
  bocharov.egor/T1/main.cpp
  bocharov.egor/T1/outputRes.cpp
  bocharov.egor/T1/outputRes.hpp
  bocharov.egor/T1/parallelogram.cpp
  bocharov.egor/T1/parallelogram.hpp
  bocharov.egor/T1/rectangle.cpp
  bocharov.egor/T1/rectangle.hpp
  bocharov.egor/T1/shape.cpp
  bocharov.egor/T1/shape.hpp
  bocharov.egor/T1/triangle.cpp
  bocharov.egor/T1/triangle.hpp
Labels: fine, gr 5, 7 out of 12

#284 sharifullina.sofia/T1
  sharifullina.sofia/T1/actionShapes.cpp
  sharifullina.sofia/T1/actionShapes.hpp
  sharifullina.sofia/T1/base-types.hpp
  sharifullina.sofia/T1/circle.cpp
  sharifullina.sofia/T1/circle.hpp
  sharifullina.sofia/T1/ellipse.cpp
  sharifullina.sofia/T1/ellipse.hpp
  sharifullina.sofia/T1/main.cpp
  sharifullina.sofia/T1/makeShape.cpp
  sharifullina.sofia/T1/makeShape.hpp
  sharifullina.sofia/T1/rectangle.cpp
  sharifullina.sofia/T1/rectangle.hpp
  sharifullina.sofia/T1/ring.cpp
  sharifullina.sofia/T1/ring.hpp
  sharifullina.sofia/T1/shape.cpp
  sharifullina.sofia/T1/shape.hpp
Labels: fine, gr 1, 7 out of 12
